apply from: "$rootDir/common-android.gradle"

dependencies {
    // Shared
    implementation(project(":app:shared:ui"))
    implementation(project(":app:shared:network"))
    implementation(project(":app:shared:navigation"))
    testImplementation(project(":app:shared:test"))
    androidTestImplementation(project(":app:shared:test"))

    // Network
    implementation(libs.ktor.core)

    testImplementation(libs.ymir.test)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.mockk.android)
    androidTestImplementation(libs.mockk.android)
}
